name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Create AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: academy
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sessionToken: ${{ secrets.AWS_SESSION_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Plan Terraform configuration
        run: terraform plan  

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Output Terraform state
        run: terraform output