name: Deploy para AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Criar perfil AWS
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: academy
          region: us-east-1
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sessionToken: ${{ secrets.AWS_SESSION_TOKEN }}
          
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Instalar Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

      - name: Inicializar Terraform
        run: terraform init -var="DB_USERNAME=${DB_USERNAME}" -var="DB_PASSWORD=${DB_PASSWORD}"

      - name: Formatar Terraform
        run: terraform fmt

      - name: Validar Terraform
        run: terraform validate -var="DB_USERNAME=${DB_USERNAME}" -var="DB_PASSWORD=${DB_PASSWORD}"

      - name: Planejar configuração do Terraform
        run: terraform plan -var="DB_USERNAME=${DB_USERNAME}" -var="DB_PASSWORD=${DB_PASSWORD}"

      - name: Aplicar configuração do Terraform
        run: terraform apply -auto-approve -var="DB_USERNAME=${DB_USERNAME}" -var="DB_PASSWORD=${DB_PASSWORD}"

      - name: Saída do estado do Terraform
        run: terraform output -var="DB_USERNAME=${DB_USERNAME}" -var="DB_PASSWORD=${DB_PASSWORD}"
